### PR TITLE
Add most recent perls to CI

### PR DESCRIPTION
**Pull request by m-dango**

### CODE REVIEW

**Comment by m-dango** [comment]
Windows seems to be lacking the more recent perls, will look into it.

**Comment by m-dango** [comment]
@exercism/reviewers Update to a github workflow.

**Comment by m-dango** [comment]
@exercism/reviewers Update to a github workflow.

**Review by ErikSchierboom — APPROVED** [review]
Neat trick with the `include`. Never saw that being used.

**Pull request merged**
