### PR TITLE
grains: Fail test when result is imprecise (fixes #239)

### LINKED ISSUE #239: Grains test doesn't handle bugs caused by `**`
This should fail the test suite:

    sub total_grains {
        return 2 ** 64 - 42;
    }

The test appears to pass for `2 ** 64`, `2 ** 64 - 1` and `2 ** 64 - 2`, which can't all be true.

This is because [`**`](https://perldoc.perl.org/perlop.html#Exponentiation) is made with C's `pow` which operates internally on doubles. The current test converts the expected value `18446744073709551615` to a double and an imprecise comparison erroneously succeeds.

The test suite should detect this and report a problem to relieve mentors of having to point it out.

Perhaps the test suite can provide a negative test,

    unlike total_grains(), qr/e\+/, "Using '**' without 'use bignum;' uses doubles that are too imprecise for this result.";

Additionally, use `'eq'` instead of `'=='` to compare the result as strings instead of numbers, since then the error message shows up as:

    #   Failed test 'returns the total number of grains on the board'
    #   at ./grains.t line 16.
    #          got: '1.84467440737096e+19'
    #     expected: '18446744073709551615'

which should more clearly indicate the problem that the lower digits have vanished.

Perhaps apply this reasoning in the test for `grains_on_square 64`, since otherwise `**` erroneously succeeds in this case, too:

    #   Failed test 'square no. 64'
    #   at ./grains.t line 23.
    #          got: '9.22337203685478e+18'
    #     expected: '9223372036854775808'

### PR DESCRIPTION
**Pull request by sshine**
Fix example solution so that it uses bignum.

### CODE REVIEW

**Comment by mienaikage** [comment]
I considered the idea of using `Math::BigInt` around the subroutine call instead of switching to `eq`, but I might be being a bit too pedantic about using `==` for numeric tests! If the tests are to use `eq`, perhaps we can simplify it and just replace `cmp_ok` with `is`?

I'm not too sure about the last `unless` test, maybe it'd be better to make a mention of `bignum` in the README instead?

**Comment by sshine** [comment]
Using `eq` the test suite does not explicitly mention `bignum` or `Math::BigInt` but relies on them to produce strings when the result cannot be contained within primitive integers.

That way the test suite can be agnostic wrt. the choice of `bignum` or `Math::BigInt`. Are you saying that there is a way to preserve this choice while using `Math::BigInt` in the test, or that the choice of library should be made for the student?

I agree that using `eq` for (big-)numeric tests is a bit cryptic. I'm also not personally big on overloading `==` for objects, since you cannot generally be sure that a particular module adds that overload, and the silent fallback is reference equality.

I think the way you typically determine that a scalar contains an integer is via e.g. `/^-?\d+$/`, so I figured that this would be a comparable way to determine that something is a number that lacks precision.

How about changing the warning to something that does not explicitly mention `bignum`, and additionally add some hints on handling big numbers in various ways?

**Comment by sshine** [comment]
As I mentioned in #239, `'eq'` makes for a pretty good error message. Could you tell me how that would look like when using `Math::BigInt`?

**Comment by sshine** [comment]
As for the last test, if `/e\+/` is not a good way to test this, perhaps one can assert that the result is not equal to 2^64 - 2. Lack of precision will cause it to be. The "expected" and "got" fields will be a little cryptic, though.

**Comment by mienaikage** [comment]
`Math::BigInt` would take the e-notated number and give back an integer, so the test would output got as `18446744073709600000` for `2 ** 64`.

**Comment by sshine** [comment]
You're not giving me concrete advice on how to change the pull request to make it pass.

What's the next step?

**Comment by mienaikage** [comment]
I'll try to give more helpful input when I have more free time to give this a proper look

**Comment by mienaikage** [comment]
1. The canonical data is currently out of date, I've opened PR https://github.com/exercism/perl5/pull/243 to update it, it'd be worth rebasing off of this.
2. The changes will need to go into the `.meta/exercise-data.yaml` file so that running the generator will apply the changes to the relevant files.
3. `use Math::BigInt`
4. Keep the `==` test as is, instead, wrap the calls to `grains_on_square` and `total_grains` e.g. `Math::BigInt->new(total_grains)`. This results in the following output:
```
not ok 8 - square no. 64

#   Failed test 'square no. 64'
#   at exercises/grains/.meta/solutions/grains.t line 24.
#          got: 9223372036854780000
#     expected: 9223372036854775808
not ok 9 - returns the total number of grains on the board

#   Failed test 'returns the total number of grains on the board'
#   at exercises/grains/.meta/solutions/grains.t line 17.
#          got: 1.84467440737096e+19
#     expected: 18446744073709551615
```
5. Instead of writing a new test, add a note to the readme and possibly a comment in the stub (is there a URL we can link to that explains it?).

**Comment by sshine** [comment]
Ok, I'll look at it when I get home from vacation.

**Comment by mienaikage** [comment]
Points 1-4 have been taken care of but I haven't got round to addressing 5 yet. Shall I merge this now to address the bug and create an issue for including more information, or would you prefer it include the additional info? I'd be happy to merge this as it is now to at least resolve the bug.

**Pull request merged**
