### PR TITLE
🤖 Add stub files to all exercises

### LINKED ISSUE #319: Create stub files for all exercises
We have decided to require all file-based tracks to provide stubs for their exercises.

The lack of stub file generates an unnecessary pain point within Exercism, contributing a significant proportion of support requests, making things more complex for our students, and hindering our ability to automatically run test-suites and provide automated analysis of solutions.

We believe that it’s essential to understand error messages, know how to use an IDE, and create files. However, getting this right as you’re just getting used to a language can be a frustrating distraction, as it can often require a lot of knowledge that tends to seep in over time. At the start, it can be challenging to google for all of these details: what file extension to use, what needs to be included, etc. Getting people up to speed with these things are not Exercism’s focus, and we’ve decided that we are better served by removing this source of confusion, letting people get on with actually solving the exercises.

The original discussion for this is at https://github.com/exercism/discussions/issues/238.

Therefore, we’d like this track to provide a stub file for each exercise.

- If this track already provides stub files for all exercises, please close this issue.
- If this track already has an open issue for creating stubs, then my apologies. Please close one as a duplicate.
- Otherwise, please respond to this issue with useful details about what needs to be done to complete this task in this track so that people who are not familiar with the track may easily contribute.

### PR DESCRIPTION
**Pull request by ErikSchierboom**
In this PR, we created (empty) stub files for all exercises that didn't yet have them.

The lack of stub file generates an unnecessary pain point within Exercism, contributing a significant proportion of support requests, making things more complex for our students, and hindering our ability to automatically run test-suites and provide automated analysis of solutions.

The original discussion for this is at exercism/discussions#238.

Closes #319

**We will automatically merge this PR in two week's time if it has not been merged by track maintainers at that point :slightly_smiling_face:**

## Tracking

https://github.com/exercism/v3-launch/issues/33

### CODE REVIEW

**Comment by m-dango** [comment]
This is likely going to conflict with https://github.com/exercism/perl5/issues/249 and https://github.com/exercism/perl5/pull/410. Once the pull request is merged most of the exercises should have stub files in place.

**Comment by ErikSchierboom** [comment]
@m-dango Well, it's not only that the stub files have to be in place, but also that the paths in the exercises' `.meta/config.json` file should be correct. Is there any harm/danger in merging this PR first?

**Comment by m-dango** [comment]
Many of the filenames will change as the generator creates them to match the file patterns in config.json. e.g. The changes in exercises/practice/secret-handshake/.meta/config.json for example will need to be undone.

Looking a bit closer, it seems that something has gone wrong with the `secret-handshake` changes. It looks like the solution file has been moved and the test is no longer able to find it, its expecting a `SecretHandshake.pm` file.

**Comment by ErikSchierboom** [comment]
> Many of the filenames will change as the generator creates them to match the file patterns in config.json. e.g. The changes in exercises/practice/secret-handshake/.meta/config.json for example will need to be undone.

Ah okay. I would then suggest to close this PR and wait for the other PRs to fix the issue of missing stubs. Agreed?

**Comment by ErikSchierboom** [comment]
@m-dango Do you perhaps have any idea when #249 will be done? I'm asking as adding the stubs to perl5 is on my v3 launch to-do list :)

**Comment by m-dango** [comment]
@ErikSchierboom I'm moving house roughly in the next couple weeks so I'm not too sure unfortunately. There is currently an outstanding PR for one of the exercises here (https://github.com/exercism/perl5/pull/417), and I'd be fine with pausing it from that point, adding the outstanding stubs for the remaining exercises separately, then putting them on the generator later, if that helps things move along.

**Comment by ErikSchierboom** [comment]
> @ErikSchierboom I'm moving house roughly in the next couple weeks so I'm not too sure unfortunately. There is currently an outstanding PR for one of the exercises here (#417), and I'd be fine with pausing it from that point, adding the outstanding stubs for the remaining exercises separately, then putting them on the generator later, if that helps things move along.

I like that suggestion.

**Comment by ErikSchierboom** [comment]
@m-dango I've rebased on the latest main and fixed the missing stub files and invalid file paths in this PR.

configlet now only complains about an empty tags array:

```
~/exercism/perl5$ ../configlet/configlet lint

The `tags` array is empty:
/home/erik/exercism/perl5/config.json
```

**Review by iHiD — APPROVED** [review]

**Pull request merged**
