### PR TITLE
Remove spacing changes from perltidy config

### PR DESCRIPTION
**Pull request by m-dango**
Spacing was reduced for display purposes on on older versions of exercism. Change the perltidy config to use the default spacing.

### CODE REVIEW

**Comment by m-dango** [comment]
@exercism/reviewers This is pretty much all whitespace change, to match online editor indent settings. (Setting github to hide whitespace changes should dramatically reduce the size of the review page).

**Comment by kotp** [comment]
I reviewed about half of it, but it would have been nicer if the whitespace changes could have been one commit, and the other(s) at least one more commit.  That would have made it a lot easier to review.

**Comment by m-dango** [comment]
Its all whitespace, via a run of `perltidy`. Unfortunately Github's whitespace option doesn't cover newlines. Outside of the perltidy config itself, its all spacing and newline changes, there is no difference in the code.

**Comment by kotp** [comment]
OK.

I was not positive because I also saw changes like this:

```diff
 --- a/exercises/practice/binary-search-tree/binary-search-tree.t
 +++ b/exercises/practice/binary-search-tree/binary-search-tree.t
 @@ -9,25 +9,21 @@ use lib $Bin, "$Bin/local/lib/perl5";
  use BinarySearchTree qw<tree treeSort>;
  
  my @test_cases = do { local $/; @{ JSON->decode(<DATA>) }; };
 +plan 11;
  
  imported_ok qw<tree treeSort> or bail_out;
  
 -subtest data => sub {
 -  for my $case ( grep { $_->{property} eq 'data' } @test_cases ) {
 -    is( tree( $case->{input}{treeData} ),
 -      $case->{expected}, $case->{description}, );
 -  }
 -};
 +for my $case (@test_cases) {
 +    if ( $case->{property} eq 'data' ) {
 +        is( tree( $case->{input}{treeData} ),
 +            $case->{expected}, $case->{description}, );
 +    }
  
 -subtest sorting => sub {
 -  for my $case ( grep { $_->{property} eq 'sortedData' } @test_cases )
 -  {
 -    is( treeSort( $case->{input}{treeData} ),
 -      $case->{expected}, $case->{description}, );
 -  }
 -};
 -
 -done_testing;
 +    elsif ( $case->{property} eq 'sortedData' ) {
 +        is( treeSort( $case->{input}{treeData} ),
 +            $case->{expected}, $case->{description}, );
 +    }
 +}
```

And you also used the words "pretty much" so I was trying to find non-whitespace changes to review.

**Review by kotp — APPROVED** [review]

**Comment by kotp** [comment]
For anyone that wants to be able to have their whitespace diff, I use this locally:

Set in `gitconfig` under alias:

```ini
dws= diff -w -U0 --word-diff-regex=[^[:space:]]
```

After I fetch the pull request locally, I then do something like this:

```sh
git dws origin/main..HEAD
```

The newer syntax will not have the `..` used.  Old habits, though, I generally use them.

**Comment by kotp** [comment]
Just to mention, the diff example was from using `git diff -b origin/main..HEAD` locally.

**Comment by m-dango** [comment]
@kotp Apologies for the use of "pretty much", I should have been clearer. "pretty much" was meant to be an exception for the config changes in `.perltidyrc`.

The `binary-search-tree.t` changes were not meant to be included, so good job for catching that. I had removed it from this branch as it was meant to be part of a separate PR.

**Comment by kotp** [comment]
It's all good.  The "pretty much" made it clear that there might be some "not so clean" things in there.  Definitely helpful communication in those two words.

**Pull request merged**
