### PR TITLE
Scrabble: Add stub, remove object-oriented cruft

### PR DESCRIPTION
**Pull request by sshine**
It does not make sense to wrap a word in a class just to call a method
on it. It is better to teach object-oriented principles by examples that
warrant the use of classes.

- Rename expected file from `Word` to `Scrabble`: When it is
  object-oriented, the entity's name makes sense to be `Word`.

- In the example solution, handle zero case with `List::Util::sum0`.

- Add stub with arguments. The case `my ($word, %extensions) = @_` is
  not something new Perl programmers will infer, and it is something
  they will learn from seeing.

### CODE REVIEW

**Comment by mienaikage** [comment]
I agree with your reasoning, and I typically do the same when updating exercises myself.

For updating an exercise, I would recommend using the generator in the `bin` directory (it looks like I mentioned it in the perl 6 readme but forgot about the perl 5 one unfortunately!). `roman-numerals` may be a good example to take a look at.

**Comment by sshine** [comment]
Thanks!

**Comment by sshine** [comment]
Hi again @mienaikage 

We're using some of the Exercism exercises for training new hires at work, and so I've wanted to update another exercise. Coming back to the track, I realize that some of those changes I want to push would end up in the same state as this PR, which I'd forgotten about.

I looked at the [Perl 6 generator README](https://github.com/exercism/perl6/blob/master/bin/README.md) now and see that what's missing in both the case of this PR and in the case of a similar PR I intend to submit for `custom-set`, is a .meta/exercise-data.yaml file.

Do I understand correctly that before I can push a change to an exercise that doesn't yet have a .meta/exercise-data.yaml, I must rewrite the existing test file into this format such that the generator can produce the .t file?

**Comment by mienaikage** [comment]
If the change is to address a bug in the exercise then adding it to the generator is not necessary, but for updates and improvements (especially if canonical data is being included) then including changes to incorporate the generator is preferred.

I've done very little on updating exercises on this track sadly, I'm currently slowly chipping away at the test2-more branch when I have the time to update the testing framework (which is mostly complete but lacking sufficient documentation to merge into master yet).

I pushed a commit to address some syntax errors, it looks like the signatures are all that need to be addressed here, I shall comment on https://github.com/exercism/perl5/pull/286 as you've raised that there.

**Comment by sshine** [comment]
Thanks. :-)

**Pull request merged**
