### PR TITLE
Add exercise generator

### PR DESCRIPTION
**Pull request by mienaikage**

### CODE REVIEW

**Comment by mienaikage** [comment]
The mustache templates were taken from the Perl 6 track and modified to generate Perl 5 exercises.

While the script works for generating Perl 5 exercises, it is currently still written in Perl 6 and should be changed.

An `example.yaml` has been created for `bob` and the generator used.

**Comment by kotp** [comment]
Should the bob generation be part of this PR?

**Comment by mienaikage** [comment]
I figured it would be good to have it alongside the generator to see that the generator works and produced data that makes sense, but this is also possible in a separate PR so I probably will separate them.

I'm also going to make further changes to the generator, as I think using `JSON` can be avoided here and it would be good to not require people to install extra modules.

**Comment by kotp** [comment]
OK, so we can use the bob generated test as a 'litmus' for this PR.

**Comment by mienaikage** [comment]
Generator now converts json to a perl hash before adding it to the test. `JSON` module no longer a requirement.

**Comment by mienaikage** [comment]
Generator is now written in Perl 5 and a readme has been included.

**Pull request merged**
