### PR TITLE
Create lasagna concept exercise

### PR DESCRIPTION
**Pull request by m-dango**

### CODE REVIEW

**Comment by kotp** [comment]
Awaiting conflict management...

**Review by kotp — COMMENTED** [review]
Should this be in "draft" mode?  The hints, instructions and introduction files are basically "to be developed" content at the moment.

**Comment by m-dango** [comment]
@kotp I moved this out of draft mode following the "minimal valid spec" here:

https://exercism.org/docs/building/tracks/concept-exercises#h-minimal-valid-spec

**Comment by kotp** [comment]
> https://exercism.org/docs/building/tracks/concept-exercises#h-minimal-valid-spec

Was aware of this, just wanted to make sure.

**Review by kotp — APPROVED** [review]

**Pull request merged**
