### PR TITLE
runs tests in their declared order

### PR DESCRIPTION
**Pull request by yanick**
Not running the tests in the orders they appear in the JSON file is confusing when comes the time to debug.

Also removed the dependency on the exception module.

Also simplified the testing code.

Also modified the output of the tests to also show the phone number as part of the description (which is also useful to know what was the problem).

### CODE REVIEW

**Comment by mienaikage** [comment]
For the first 2 points, the Test2::Tools::Exception module is included as part of the Test2:V0 bundle, which should be included in the installation steps shortly. We can then remove the eval and have the tests run in order. However, I did consider separating the success and error tests into subtasks. Is having the tests run in order is preferable? I would think the description of the test would be suitable enough to identify a failing test?

Having separate map steps just for dereferencing seems odd to me, what makes it simpler than dereferencing what goes into the map directly?

For showing the phone number as part of the description, perhaps it would be simpler to leave the description in the data unchaged and give `"$desc - $input"` as the argument to the test instead?

**Comment by yanick** [comment]
> Is having the tests run in order is preferable? I would think the description of the test would be suitable enough to identify a failing test?

I indeed think that running tests in the order they are listed is preferable, as it's the reasonable expectation people have. If we think that order doesn't make sense, then the order should be changed in the JSON itself.


> Having separate map steps just for dereferencing seems odd to me, what makes it simpler than dereferencing what goes into the map directly?

Separation of concern. Instead of having a single step where several things are done concurrently, each logical operation is done separately.

> For showing the phone number as part of the description, perhaps it would be simpler to leave the description in the data unchaged and give "$desc - $input" as the argument to the test instead?

Not to my eye, but meh, feel free to tweak to your preference.

**Comment by rfilipo** [comment]
@yanick, please, can you change your code using Test2::V0 instead of Test::More to reach our current development goals? Thank you.

**Comment by mienaikage** [comment]
I propose the following:
```
my @cases  = (
  map { [ $_->{input}{phrase}, $_->{expected}, $_->{description} ] }
  map {@$_}
  map { $_->{cases} } @{ $C_DATA->{cases} }
);

for (@cases) {
  my ( $input, $expected, $desc ) = @$_;
  $desc .= " - $input";

  !ref $expected
    ? is clean_number($input), $expected, $desc

    : like dies( sub { clean_number($input) } ),
    qr/$expected->{error}/, $desc;
}
```

It retains the simplicity of the tests while reducing the complexity of the map, in my opinion.

**Comment by yanick** [comment]
```
 !ref $expected
    ? is clean_number($input), $expected, $desc

    : like dies( sub { clean_number($input) } ),
    qr/$expected->{error}/, $desc;
```

Using the trinary operator in void context is kinda like using a `$foo && ....` instead of a `if ( $foo ) { ... }`; it works, but it's not usually recommended. Ditto for `! $foo ? this() : that()` instead of `$foo ? that() : this()`. 

I'll change the test case to use Test2::V0. For the rest, I'll let you peeps tweak the Pr to your liking.

**Pull request merged**
