### PR TITLE
Don't mention a constructor in a non-OOP module

### PR DESCRIPTION
**Pull request by choroba**

### CODE REVIEW

**Comment by rfilipo** [comment]
Hi, @choroba , thank you for your help. I don't believe it's necessary to mention the constructor here. Why do you mean that?

**Comment by choroba** [comment]
The error message is misleading. The test doesn't check the existence of the constructor, nor does it construct any object of the class; on the contrary: it calls a subroutine reference created from the fully qualified name. So, I propose to remove the mention of the constructor in the error message.

**Comment by mienaikage** [comment]
It looks like it might have just been a mistake when the exercise was created, I don't think there ever was a constructor for this exercise.

https://github.com/exercism/perl5/commit/18bfddf9c968d1b4224bda177934d7b4f4473766

**Comment by choroba** [comment]
Yes, it was probably copied from a different exercise which needed it and the author forgot to edit the message.

**Comment by rfilipo** [comment]
Yes, I agree. Ok.

**Review by rfilipo — APPROVED** [review]
Done.

**Pull request merged**
