### PR TITLE
Include say function for debugging in online editor

### PR DESCRIPTION
**Pull request by m-dango**

### CODE REVIEW

**Comment by m-dango** [comment]
@exercism/reviewers Support for the `output` key has been added to the test runner. The `say` function looks to work best for making use of it.

**Review by ErikSchierboom — APPROVED** [review]
Great! Two small suggestions:

1. I'd add a test case to the test runner to verify this (ignore this if it was done already, but my [google-fu](https://github.com/exercism/perl5-test-runner/search?q=output) didn't find anything)
2. Could you document this in the `exercises/shared/.docs/debug.md` file? See https://exercism.org/docs/building/tracks/shared-files#h-file-debug-md for the docs

**Comment by m-dango** [comment]
@ErikSchierboom There should be a test on the output in example-success IIRC, but its using `print` instead of `say`. Using `print` can work, but without an explicit newline the output all gets concatenated into a single output in the log file and it can't be associated with individual tests.

**Comment by ErikSchierboom** [comment]
@m-dango Ah yes, I missed it: https://github.com/exercism/perl5-test-runner/blob/main/tests/example-success/expected_results.json#L16

**Pull request merged**
