### PR TITLE
Add armstrong-numbers exercise

### PR DESCRIPTION
**Pull request by glennj**
I don't know if this is the right approach for this exercise. Does the code need some type checking?

### CODE REVIEW

**Review by kotp — APPROVED** [review]
Not sure type indicators would be helpful here, either.  Armstrong technically should work with other base numbers other than base 10.

**Comment by glennj** [comment]
Just because of the use of `bignum` in the tests, the example solution relies on the parameter being a `Math::BigInt`. Ah well, TDD.

**Comment by kotp** [comment]
Let's get it in and adjust after getting some information in terms of mentoring/review of the exercise.

**Comment by m-dango** [comment]
I will have another look at this later, but I may make some modifications such as adding `packages-and-modules` as a prerequisite, or using explicit BigInt objects as the argument in the tests (because it won't be obvious in the web UI that objects are being passed in).

**Pull request merged**
